name: Check Changed Solutions

on:
  workflow_dispatch:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install colordiff libssl-dev libpcre3 libpcre3-dev

      - name: Checkout V
        uses: actions/checkout@v4
        with:
          repository: vlang/v

      - name: Build V
        run: make && ./v symlink

      - name: Checkout V AoC repo
        uses: actions/checkout@v4
        with:
          path: aoc
          fetch-depth: 0

      - name: Install dependencies
        run: v install pcre

      - name: Run verify.v to check solutions
        run: cd aoc && CHANGED=1 v run verify.v

      - name: Check .v formatting
        run: v fmt . -c
